### ISSUE TITLE
Acrescentar badge do gitter ao README

### ISSUE THREAD

**Issue by waldyrious** [JuliaLangPt/tutorial#1]
Para facilitar a descoberta do canal: https://gitter.im/JuliaLangPt/julia

(pode ser colocado aqui ou no repositório [julia](https://github.com/JuliaLangPt/julia) -- ou em ambos!)

**Comment by jmarcellopereira** [comment]
opa, ja add ;)

**Comment by ScottPJones** [comment]
Voces sabem como fazer isso?

**Comment by waldyrious** [comment]
@ScottPJones basta acrescentar este código no readme:

    [![Gitter](https://badges.gitter.im/JuliaLangPt/julia.svg)](https://gitter.im/JuliaLangPt/julia?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by jmarcellopereira** [comment]
@waldyrious em qual parte eu coloco o código no redme? (sou novo nesse negócio, heheheh)

**Comment by waldyrious** [comment]
@jmarcellopereira foi por essa questão que eu próprio não fiz a alteração :) há quem coloque antes do título, há quem coloque os badges imediatamente abaixo. É uma decisão editorial, mas por norma coloca-se perto do topo para maximizar a visibilidade e utilidade.

**Comment by jmarcellopereira** [comment]
@waldyrious coloquei no topo, mas como nao tenho experiencia no git nao sei se ficou bom.

**Comment by waldyrious** [comment]
@jmarcellopereira [excelente](https://github.com/JuliaLangPt/tutorial_PT_BR/commit/1a69f4d) :) eu só melhoraria o commit message para ser mais específico, mas fora isso ficou bem. Pode-se fechar o issue :D

**Comment by jmarcellopereira** [comment]
@waldyrious  ;) tranquilo, uma boa dica
